### ISSUE TITLE
Χρήση της κάμερας

### ISSUE THREAD

**Issue by ivanelrey** [ivanelrey/SnapFarm#5]
Μετα από το πάτημα ένος κουμπιού στην αρχική οθόνη(snap) ο χρήστης θα έχει την δυνατότητα να επιλέξει αν θέλει να ανεβάσει αρχείο απο κάποιο φάκελο η να χρησιμοποιήσει την κάμερα.

**Comment by Tolis01** [comment]
ο χρήστης έχει την δυνατότητα χρησιμοποιήσει την κάμερα.
